# GPIO Configuration
[gpio]
pin = 17
debounce_delay_secs = 5

# Web Monitor Configuration
[web_monitor]
port = 8080
enabled = true

# Logging Configuration
[logging]
level = "info"
file_path = "logs/noisebell.log"
max_buffered_lines = 10000

# Monitor Configuration
[monitor]
monitor_type = "web"

# Endpoint Configuration
[endpoint]
url = "https://noisebell.jetpham.com/api/status"
timeout_secs = 30
retry_attempts = 3 